/* NDS.Init — public surface
 * Rides: (none — this is the orchestrator every component registers with)
 * Methods:
 *   NDS.Init.initialize()      run the full init pass (called automatically on DOM ready)
 *   NDS.Init.components        the component registry: {name, selector, init, critical}
 *                              (init defaults to NDS[name].init(); selector null = every page;
 *                              + optional lazy() — arm the trigger instead of fetching the
 *                              bundle, which needs its OWN bundle or a sibling pulls it anyway;
 *                              + optional eager() to opt an instance back in;
 *                              + optional refresh(root) — owner hook for NDS.Init.refresh;
 *                              + optional destroy(root) / destroyEach / destroySelector —
 *                              NDS.Init.destroy hooks for components with no element backref)
 *   NDS.Init.config            the resolved config
 *   NDS.Init.audit()           run the debug audits (nds-audit.js). First call loads the
 *                              audit bundle and returns a promise; later calls are synchronous.
 *   NDS.Init.refresh(el)       el's CHILDREN changed (rows/cards added or removed) — re-scan
 *                              every live component. Omit el for the whole document
 *   NDS.Init.mount(el)         el's markup is NEW to the page: load the bundles its content
 *                              needs, then init them against it → Promise
 *   NDS.Init.destroy(el)       tear down every instance inside el before it leaves the page.
 *                              Returns how many instances it destroyed
 *   NDS.loadBundle(name)       load one injected bundle on demand → Promise
 * Events:
 *   (none)
 * Hooks (window globals — set these BEFORE the bundle loads):
 *   window.NDSInitConfig   {autoInitialize, disableAll, enableLogging, enableTiming, initBudgetMs}
 *   window.NDSAssetBase    override the directory the injected bundles load from
 *   window.__NDS_BUNDLES   the build-generated bundle manifest — never hand-write it
 *   written by the loader: data-nds-loaded on <html> — the reveal stamp, set once the
 *                          main CSS has applied; data-paged-split on each .nds-paged-content
 *                          at init (items past its --per-page, else 6, get hidden);
 *                          data-swiper-preset on each swiper, with --slides and the
 *                          peek state its init will pick, and data-swiper-single when its
 *                          slides fit one page; in RTL each multi-page track is pinned to
 *                          scrollLeft 0 after the stamp (WebKit lands it at its end)
 * Gotchas:
 *   - nds-main.min.js is a defer script and GATES the reveal; every other bundle is
 *     injected after it or pulled on demand.
 *   - A component whose bundle has not arrived answers through a lazy stub: a method
 *     call loads the bundle and returns a Promise. A synchronous READ gets a truthy
 *     stub, so main-bundle code that reads an API synchronously keeps it in main.
 *   - refresh() skips a stubbed namespace on purpose — it scans the DOM when it lands.
 *     Content built after detection needs mount(), which fetches the bundle.
 *   - refresh() re-scans what stays; destroy() releases what leaves. A framework route
 *     that swaps views needs destroy(), or every instance keeps its listeners alive.
 *   - Bundle membership is generated by the build. Never hardcode it in JS.
 */
(() => {
    'use strict';

    // Array order = init order within each tier (critical → deferred idle drain →
    // each injected bundle's group on arrival). `name` must equal the NDS namespace:
    // it keys the default init and the build manifest lookup.
    // Each `critical` / deferred note says why the component is safe (or not) to init late.
    const COMPONENTS = [
        {
            name: 'Mainnav',
            selector: '.nds-main-nav',
            // Owner hook: the container passed is usually the view INSIDE the chrome, and
            // a plain init() would no-op on the stale guard after a route change.
            refresh: () => NDS.Mainnav?.reinit?.(),
        },
        {
            // Deferred: the inline head script stamps the saved theme pre-paint; init only syncs the toggle UI.
            name: 'Theme',
            selector: '[data-theme-toggle], #ndsThemeToggle, [data-theme-value]',
        },
        {
            // Critical: init un-hides [hidden] form wrappers and reveals .nds-clear on pre-filled fields (CLS if late).
            name: 'Forms',
            selector: '.nds-form-control',
            critical: true,
        },
        {
            // Deferred but in main: init restores JS-derived labels, which would flash empty behind a bundle fetch.
            name: 'CustomSelect',
            selector: '.nds-select-input',
        },
        {
            // Extras: the field paints complete with no JS; the panel is built on first open.
            name: 'TimePicker',
            selector: '.nds-time-input',
        },
        {
            // Deferred: input wiring fires on typing; an autofocus restore lands one idle slot later.
            name: 'OTP',
            selector: '.nds-otp-group',
        },
        {
            // Deferred: chips ship at data-status="neutral"; init's check() recomputes from the current value.
            name: 'Password',
            selector: '.nds-form-container.nds-password',
        },
        {
            name: 'Tabs',
            selector: '.nds-tabs',
        },
        {
            // Deferred: the wrapper reparent is layout-neutral; clicks in the gap no-op and recover.
            // No refresh hook on purpose: re-applying a sort would re-order a server-sorted page by cell text.
            name: 'Tables',
            selector: '.nds-table',
        },
        {
            // Deferred: default-open panels ship data-state="open", so CSS paints them with no JS.
            name: 'Accordion',
            selector: '.nds-accordion',
        },
        {
            // Delegated: the skeleton is keyed on the stepper's own stamp; layout is CSS alone.
            name: 'Stepper',
            selector: '.nds-stepper',
        },
        {
            // Delegated: crit + presetSwipers reserve the final row, so init releases into reserved space.
            name: 'Swiper',
            selector: '.nds-swiper',
            destroyEach: true,
        },
        {
            name: 'Upload',
            selector: '.nds-file-upload',
        },
        {
            // Deferred: recognition starts on click, so a late wire lands first.
            name: 'VoiceInput',
            selector: '.nds-voice-input',
        },
        {
            // Critical: init un-hides the mobile toggle and fills its label (CLS if late).
            name: 'Sidemenu',
            selector: '.nds-sidemenu',
            critical: true,
        },
        {
            // Critical: the hero-aside variant jumps from its -180px placeholder if positioned late.
            name: 'Sideinfo',
            selector: '.nds-sideinfo',
            destroyEach: true,
            critical: true,
        },
        {
            // Critical: init expands the active-page path; late = the path pops open post-paint.
            name: 'Drawer',
            selector: '.nds-drawer',
            destroyEach: true,
            critical: true,
        },
        {
            // Critical: data-toc-source builds the list at init; its height is unknown, so no skeleton can reserve it.
            name: 'Toc',
            selector: '.nds-toc',
            destroyEach: true,
            critical: true,
        },
        {
            // Critical: the overflow affordance would pop in post-reveal on above-the-fold tab bars.
            name: 'ScrollMore',
            selector: '.nds-scroll-more',
            destroyEach: true,
            critical: true,
        },
        {
            // Deferred: cosmetic on-scroll animation.
            name: 'Progress',
            selector: '.nds-progress-circle, .nds-progress-bar',
        },
        {
            // Deferred: cosmetic on-scroll animation.
            name: 'Numbers',
            selector: '.nds-number-format, .nds-counter-value',
        },
        {
            // Docs-only, own bundle: _code.scss paints the box and gutter with no JS.
            // `.nds-code`, not bare `code`, so detection doesn't sweep every inline <code>.
            name: 'Code',
            selector: '.nds-code',
        },
        {
            name: 'Copy',
            selector: '.nds-copy',
        },
        // Showcase is not registered: it self-boots from its own defer tag, which may run after this init.
        {
            // nds-tables starts it for a table's header select-all, stamped after detection.
            name: 'Selection',
            selector: '[data-selection-target]',
            // Owner hook: counters and select-all boxes live OUTSIDE the list they count.
            refresh: () => NDS.Selection?.refresh?.(),
        },
        {
            name: 'Share',
            selector: '.nds-share',
        },
        {
            // Detection-only: a [data-export] button loads the bundle; init wires the delegated click.
            name: 'Export',
            selector: '[data-export]',
        },
        {
            name: 'DatePicker',
            selector: '.nds-date-input',
        },
        {
            // Critical: tags external links with no layout reads. Keep it read-free — a
            // getBoundingClientRect here once forced a full layout (~110ms@6.6x).
            name: 'Link',
            selector: null,
            critical: true,
        },
        {
            // Lazy, every page: a visitor with a stored choice fetches nothing. Consent itself is NDS.Cookies in main.
            name: 'CookieConsent',
            selector: null,
            lazy: () => {
                document.addEventListener('click', (e) => {
                    const btn = e.target.closest('[data-cookies-toggle]');
                    if (!btn) return;
                    e.preventDefault();
                    NDS.CookieConsent.open(btn.dataset.cookiesToggle || undefined, btn);
                });
            },
            eager: () => !NDS.Cookies.getConsent() && !NDS.Cookies.get('cookieConsentDismissed'),
        },
        {
            // Deferred: stars paint from markup; nothing else reads NDS.Rating.
            name: 'Rating',
            selector: '.nds-rating',
        },
        {
            // Deferred: the native range works with no JS; init only paints the fill and <output>.
            name: 'Slider',
            selector: '.nds-slider',
            destroyEach: true,
            // The stamp and resize subscription live on the container, not the scanned input.
            destroySelector: '.nds-slider-container',
        },
        {
            // Deferred: the collapsed clamp is pure CSS; the measure runs in the ResizeObserver.
            name: 'Expandable',
            selector: '.nds-expandable',
        },
        {
            // Delegated: crit shapes 6+ trails to the post-collapse geometry, so init swaps in place.
            name: 'Breadcrumb',
            selector: '.nds-breadcrumb-nav',
        },
        {
            name: 'Dropmenu',
            selector: '.nds-dropmenu',
        },
        {
            name: 'Tooltip',
            selector: '.nds-tooltip',
        },
        {
            // Critical: pre-selected chips are JS-built and grow the field (CLS if late).
            name: 'Multiselect',
            selector: '.nds-multiselect',
            critical: true,
        },
        {
            // Critical: restored chips CLS if late, and in a pre-bundle gap Enter native-submits the form.
            name: 'TagInput',
            selector: '.nds-taginput',
            critical: true,
        },
        {
            // Deferred: results fetch on typing.
            name: 'Autocomplete',
            selector: '.nds-form-container[data-url]',
        },
        {
            // Own bundle: the _editor.scss skeleton holds the field until the stamp lands.
            name: 'Editor',
            selector: '.nds-editor',
        },
        {
            // Delegated: crit hides each [data-filter-items] until its own stamp, which lands after
            // applyUrlParams(), so a URL filter never flashes the full list. MUST stay before Pagination:
            // it stamps data-filtered before Pagination reads items. Keyed on the target, not
            // .nds-filter, so a search-only filter still inits.
            name: 'Filter',
            selector: '[data-filter-target]',
            // Owner hook: a filter is keyed by its target and its UI sits outside the list.
            refresh: (root) => NDS.Filter?.refresh?.(root),
        },
        {
            // After Filter and Tables, so each claims its own list first. Owner hook: the buttons sit outside the list.
            name: 'Sort',
            selector: '[data-sort-target]',
            refresh: (root) => NDS.Sort?.refresh?.(root),
        },
        {
            // Delegated: crit shows the first page (presplitPaged) and _pagination.scss reserves the nav row.
            name: 'Pagination',
            selector: '.nds-pagination',
            init: () => { NDS.Pagination?.init?.(); NDS.Pagination?.initAuto?.(); },
            destroyEach: true,
        },
        {
            name: 'Ipv',
            selector: '.nds-ipv-thumbnail',
        },
        {
            name: 'Modal',
            // .nds-modal-template keeps the gate true for a modal shipped inert in a <template>.
            selector: '.nds-modal, .nds-modal-template',
            // Listeners are delegated on document; this releases the OPEN state (backdrop, scroll lock).
            destroy: (root) => NDS.Modal?.destroy?.(root),
        },
        {
            name: 'Alert',
            selector: '.nds-alert',
        },
        {
            // Delegated: the panel ships [hidden]; toggle clicks in the gap no-op and recover.
            name: 'Panel',
            selector: '.nds-panel, .nds-panel-template',
            destroyEach: true,
        },
        {
            name: 'UserFeedback',
            selector: '.nds-user-feedback',
        },
        {
            name: 'Chart',
            selector: '.nds-chart',
        },
        {
            // Critical: init BUILDS the placeholder into empty containers (CLS if late).
            name: 'Empty',
            selector: '.nds-empty',
            critical: true,
        },
        {
            // Critical: a click in the deferred gap would bypass the single-submit cooldown.
            name: 'CooldownButton',
            selector: '.nds-cooldown',
            critical: true,
        },
        {
            // Delegated beside the panels it toggles; its own `hidden` prevents a pre-dock flash.
            name: 'Fab',
            selector: '.nds-fab, .nds-fab-dock',
            // Docked FABs left root for <body>, so only the component knows which belong to the view.
            destroy: (root) => NDS.Fab?.destroy?.(root),
        },
        // Topbar widgets last: non-critical chrome, network- or interaction-bound.
        {
            // Delegated: the panel ships [hidden]; CSS owns the expand.
            name: 'DigitalStamp',
            selector: '.nds-digital-stamp-tab',
        },
        {
            name: 'CityWeather',
            selector: '#nds-weatherInfo, #nds-cityName',
        },
        {
            name: 'TimeDate',
            selector: '#nds-date, #nds-realTimeClock',
        },
        {
            // Lazy: the FAB is on every page but most visitors never open the panel.
            // eager() opts a returning visitor in, so their saved modes apply at load.
            name: 'Accessibility',
            selector: '[data-accessibility-toggle]',
            // Capture, so Panel (the FAB is also a [data-panel-toggle]) never acts before the bundle.
            // Read __ndsStub FIRST: every property on a stub is a truthy function, so a bare .ready lies.
            lazy: (bundle) => {
                document.addEventListener('click', (e) => {
                    const btn = e.target.closest('[data-accessibility-toggle]');
                    if (!btn) return;
                    const ns = NDS.Accessibility;
                    if (ns && !ns.__ndsStub && ns.ready) return;
                    e.stopPropagation();
                    NDS.State?.add?.(btn, 'loading');
                    // Explicit so the paired stylesheet starts with the script, not after it.
                    NDS.loadBundle(bundle);
                    NDS.Accessibility.toggle(btn);
                }, true);
            },
            eager: () => { try { return !!localStorage.getItem('nds-a11y'); } catch (e) { return false; } },
        },
    ];
    for (const c of COMPONENTS) c.init ||= () => NDS[c.name]?.init?.();

    // scheduler.yield() lets input/paint preempt between batches; the fallback channel
    // is allocated once per page so SPA reinits don't leak channels.
    const _yieldChannel = new MessageChannel();
    const _yieldQueue = [];
    _yieldChannel.port1.onmessage = () => {
        const cb = _yieldQueue.shift();
        if (cb) cb();
    };
    const yieldToBrowser = (typeof scheduler !== 'undefined' && scheduler.yield)
        ? (cb) => scheduler.yield().then(cb)
        : (cb) => { _yieldQueue.push(cb); _yieldChannel.port2.postMessage(null); };

    // ponytail: rIC fallback for Safari fires almost at once, not at true idle; the 5ms slot
    // still caps each task. The slot starts when the callback FIRES — timed from scheduling,
    // setTimeout's 4ms clamp left ≤1ms and drain re-queued forever.
    const scheduleIdle = window.requestIdleCallback ||
        ((cb) => setTimeout(() => {
            const start = performance.now();
            cb({
                didTimeout: false,
                timeRemaining: () => Math.max(0, 5 - (performance.now() - start))
            });
        }, 1));

    // Captured at eval: currentScript is main's own tag here and null in any callback.
    // Siblings reuse main's origin (passes a CSP host allowlist) and its ?ver= cache-bust.
    const SELF = document.currentScript ||
        [...document.scripts].find((s) => /nds-main(\.min)?\.js/.test(s.src));
    const ASSET = (() => {
        if (SELF && SELF.src) {
            const u = new URL(SELF.src, location.href);
            return { dir: u.href.slice(0, u.href.lastIndexOf('/') + 1), ver: u.search };
        }
        return { dir: window.NDSAssetBase || '', ver: '' };
    })();
    const bundleUrl = (file) => ASSET.dir + file + ASSET.ver;

    // Build-generated: { delegated: { file, ns:[...], css?:[...] }, ... }.
    const MAP = window.__NDS_BUNDLES || {};
    const nsToBundle = {};
    for (const b in MAP) for (const ns of (MAP[b].ns || [])) nsToBundle[ns] = b;

    // Trusted Types sink for script.src. A policy name the consumer did not allowlist
    // falls back to a plain string for their default policy.
    let _ttPolicy;
    if (window.trustedTypes && trustedTypes.createPolicy) {
        try {
            _ttPolicy = trustedTypes.createPolicy('nds', { createScriptURL: (u) => u });
        } catch (e) { /* policy name not allowed — fall back to plain string */ }
    }

    // The CSS folder, not the JS one, which a consumer's bundler may move. Marker first
    // (the preload never gets a `.sheet`); two queries, because a comma list resolves by
    // document order and the earlier preload would win.
    function mainCssLink() {
        return document.querySelector('link[data-nds-defer="main"]')
            || document.querySelector('link[href*="nds-main.min.css"]');
    }

    // Loaded from this bundle, not an inline script, so a strict CSP needs no extra grant.
    // Dedupe by pathname over stylesheet links: a self-hosted sheet won't match our ?ver,
    // and document.styleSheets misses one still downloading.
    function addSheet(name) {
        const main = mainCssLink();
        const url = main
            ? main.href.replace('nds-main.min.css', name)
            : ASSET.dir.replace(/\/js\/?$/, '/css/') + name + ASSET.ver;
        let path;
        try { path = new URL(url, location.href).pathname; } catch (e) { return null; }
        const dup = [...document.querySelectorAll('link[rel="stylesheet"]')]
            .some((l) => { try { return new URL(l.href, location.href).pathname === path; } catch (e) { return false; } });
        if (dup) return null;
        const l = document.createElement('link');
        l.rel = 'stylesheet';
        l.href = url;
        document.head.appendChild(l);
        return l;
    }

    // Idempotent; resolves on load OR error so callers never hang. A failed fetch is
    // removed and uncached, so the lazy stub can retry once.
    const _bundlePromises = {};
    function loadBundle(name) {
        if (_bundlePromises[name]) return _bundlePromises[name];
        const file = MAP[name] && MAP[name].file;
        // Sheets first, before any early return: a self-hosted or inlined bundle still needs them.
        if (MAP[name]) for (const sheet of MAP[name].css || []) addSheet(sheet);
        if (!file || !ASSET.dir) return (_bundlePromises[name] = Promise.resolve());
        // Self-hosted under a no-injection CSP: their own <script> tag, our init.
        if ([...document.scripts].some((s) => s.src && s.src.includes(file))) {
            return (_bundlePromises[name] = Promise.resolve());
        }
        // Inlined or concatenated into the consumer's build: every namespace already real.
        const bundleNs = MAP[name].ns || [];
        if (bundleNs.length && bundleNs.every((n) => NDS[n] && !NDS[n].__ndsStub)) {
            return (_bundlePromises[name] = Promise.resolve());
        }
        _bundlePromises[name] = new Promise((resolve) => {
            const url = bundleUrl(file);
            const s = document.createElement('script');
            s.src = _ttPolicy ? _ttPolicy.createScriptURL(url) : url;
            s.fetchPriority = 'low';
            if (SELF && SELF.nonce) s.nonce = SELF.nonce;
            s.onload = resolve;
            s.onerror = () => {
                console.warn(`[NDS] bundle '${name}' failed to load (${url})`);
                s.remove();
                delete _bundlePromises[name];
                resolve();
            };
            (document.body || document.head).appendChild(s);
        });
        return _bundlePromises[name];
    }

    // Lazy stubs: NDS.X.method() before its bundle arrives loads it and replays the call
    // (returning a Promise). The bundle overwrites the stub when it runs.
    for (const ns in nsToBundle) {
        if (NDS[ns]) continue;
        const bundle = nsToBundle[ns];
        NDS[ns] = new Proxy({ __ndsStub: true }, {
            get(target, prop) {
                if (prop === '__ndsStub') return true;
                if (prop === 'then' || typeof prop === 'symbol') return undefined;
                return (...args) => loadBundle(bundle).then(() => {
                    const real = NDS[ns];
                    if (real && !real.__ndsStub && typeof real[prop] === 'function') {
                        return real[prop](...args);
                    }
                    // Caller error (no such method) vs a bundle that never arrived.
                    if (real && !real.__ndsStub) {
                        console.warn(`[NDS] ${ns}.${String(prop)} is not a method of NDS.${ns} — its surface: ${Object.keys(real).join(', ')}`);
                    } else {
                        console.warn(`[NDS] ${ns}.${String(prop)}() unavailable — bundle '${bundle}' missing`);
                    }
                });
            },
        });
    }

    // Hide items past each container's inline --per-page (else crit's 6) at init, not at
    // the reveal: main CSS can land first, and the skeleton jumped from 6 to --per-page.
    // Inline only — a computed read would force a recalc.
    function presplitPaged() {
        document.querySelectorAll('.nds-paged-content:not([data-paged-initialized], [data-paged-split])').forEach(c => {
            // A negative value would index items[-1] and throw before the reveal.
            const v = parseInt(c.style.getPropertyValue('--per-page'), 10);
            const n = v > 0 ? v : 6;
            // Pagination's _pagedItems: a tbody counts its own rows only (sub-rows ride their parent).
            const items = c.tagName === 'TBODY'
                ? Array.from(c.children).filter(el => el.classList.contains('nds-page-item') && !el.classList.contains('nds-sub'))
                : c.querySelectorAll('.nds-page-item');
            for (let i = n; i < items.length; i++) items[i].hidden = true;
            c.setAttribute('data-paged-split', '');
        });
    }

    function initializeNDS() {
        if (CONFIG.disableAll === true) {
            if (CONFIG.enableLogging) {
                console.warn('[NDS] Initialization disabled (config.disableAll = true)');
            }
            return;
        }
        const startTime = performance.now();
        presplitPaged();

        let criticalComponents, deferredComponents, injectedGroups;

        const runInit = (component) => {
            const start = CONFIG.enableTiming ? performance.now() : 0;
            try {
                component.init();
                if (CONFIG.enableLogging) {
                    const timing = CONFIG.enableTiming
                        ? ` ${(performance.now() - start).toFixed(1)}ms`
                        : '';
                    console.log(`[NDS:init] ${component.name}${timing}`);
                }
            } catch (error) {
                console.warn(`[NDS:init] ${component.name} failed:`, error);
            }
        };

        // The reveal: stamp data-nds-loaded only once main CSS has applied, so the stamp
        // means "styled + inited". window.load is the backstop so the reveal can't hang.
        function stampWhenStyled() {
            const root = document.documentElement;
            const main = mainCssLink();
            // Size each swiper's skeleton row to what nds-swiper.js will pick (same knobs,
            // same breakpoints), so init moves nothing. The stamp releases crit's guards.
            const presetSwipers = () => {
                const tier = matchMedia(NDS.breakpoints.desktop).matches ? 'max'
                    : matchMedia(NDS.breakpoints.tablet).matches ? 'mid' : 'min';
                const tracks = [];
                document.querySelectorAll('.nds-swiper:not([data-nds-swiper-initialized], [data-swiper-preset])').forEach(s => {
                    // Inline knob first, the deprecated bare attribute second.
                    const knob = (prop, attr) => parseInt(s.style.getPropertyValue(prop)) || parseInt(s.getAttribute(attr)) || 0;
                    const per = s.classList.contains('nds-spotlight') ? 1 : knob(`--${tier}-slides`, 'slides-' + tier) || 1;
                    const peek = knob('--peek', 'peek');
                    // Own slides only: a swiper nested in a slide must not add pages.
                    const w = s.querySelector('.nds-swiper-wrapper');
                    const pages = Math.ceil((w ? w.querySelectorAll(':scope > .nds-swiper-slide').length : 0) / per);
                    s.style.setProperty('--slides', per);
                    if (peek && s.hasAttribute('peek')) s.style.setProperty('--peek', `${peek}px`);
                    s.toggleAttribute('data-swiper-peek', peek > 0 && pages > 1);
                    // One page: init keeps the nav hidden, so its reserve goes now.
                    s.toggleAttribute('data-swiper-single', pages <= 1);
                    s.setAttribute('data-swiper-preset', '');
                    if (pages > 1 && NDS.isRTL) tracks.push(w);
                });
                return tracks;
            };
            // Idempotent: three listeners race to get here.
            const done = () => {
                if (root.hasAttribute('data-nds-loaded')) return;
                const tracks = presetSwipers();
                root.setAttribute('data-nds-loaded', '');
                // WebKit RTL lands a newly overflowing track at its END; the first write
                // rides the reveal's own recalc. Same double write as nds-swiper.js.
                tracks.forEach(w => {
                    if (!w) return;
                    w.style.scrollBehavior = 'auto';
                    w.scrollLeft = 0;
                    void w.offsetHeight;
                    w.scrollLeft = 0;
                    void w.offsetHeight;
                    w.style.scrollBehavior = '';
                });
                if (!main) return;
                addSheet('nds-icons.min.css'); // no-op once requested; covers a main CSS error
                loadHgiSheet();
            };
            // A load event that already fired must not strand the reveal on window.load.
            if (!main || main.sheet) { done(); return; }
            main.addEventListener('load', done, { once: true });
            main.addEventListener('error', done, { once: true });
            window.addEventListener('load', done, { once: true });
        }

        // Icon tokens sit on :root, so a late write restyles the whole tree. Requested as
        // main CSS applies, they arrive during the critical pass and ride the reveal's recalc.
        function loadIconTokens(main) {
            if (!main) return;
            const go = () => addSheet('nds-icons.min.css');
            if (main.sheet) go();
            else main.addEventListener('load', go, { once: true });
        }

        // After the reveal, so the font fetch stays out of the LCP window.
        function loadHgiSheet() {
            if (document.fonts) {
                // Safari won't load the fallback face while the primary is loading.
                document.fonts.load('1em "hgi-blank"', '\u{F0000}').catch(() => {});
                // Icons that all start hidden (a closed tab panel) would never start the fetch.
                document.fonts.load('1em "hgi-stroke-rounded"', '\u{F0000}').catch(() => {});
            }
            addSheet('hgi-rounded-stroke-min.css');
        }

        // Critical pass: time-sliced, yields once the per-batch budget is spent.
        let criticalIndex = 0;
        function initCriticalBatch() {
            const batchStart = performance.now();
            while (
                criticalIndex < criticalComponents.length &&
                performance.now() - batchStart < CONFIG.initBudgetMs
            ) {
                runInit(criticalComponents[criticalIndex++]);
            }
            if (criticalIndex < criticalComponents.length) {
                yieldToBrowser(initCriticalBatch);
            } else {
                // Main's deferred list never waits on a bundle fetch or the reveal.
                if (deferredComponents.length) drainList(deferredComponents, logAllDone);
                else logAllDone();

                // Each bundle's group inits on its own arrival.
                for (const name in injectedGroups) {
                    const group = injectedGroups[name];
                    loadBundle(name).then(() => drainList(group));
                }

                stampWhenStyled();
            }
        }

        // Runs a list across idle slots; the timeout covers a page that never idles.
        function drainList(list, onDone) {
            let i = 0;
            function drain(deadline) {
                while (
                    i < list.length &&
                    (deadline.didTimeout || deadline.timeRemaining() > 1)
                ) {
                    runInit(list[i++]);
                }
                if (i < list.length) scheduleIdle(drain, { timeout: 2000 });
                else if (onDone) onDone();
            }
            scheduleIdle(drain, { timeout: 2000 });
        }

        function logAllDone() {
            if (CONFIG.enableTiming) {
                console.log(
                    `[NDS] All components initialized in ${Math.round(performance.now() - startTime)}ms`
                );
            }
        }

        // No rAF before detection: the page is hidden until the reveal anyway, and rAF
        // never fires in a background tab, which would never initialize.
        criticalComponents = [];
        deferredComponents = [];
        injectedGroups = {};
        for (const c of COMPONENTS) {
            const present = !c.selector || document.querySelector(c.selector);
            if (!present) continue;
            if (c.critical) {
                criticalComponents.push(c);
                continue;
            }
            const bundle = nsToBundle[c.name];
            // Armed even when eager: a press while that bundle is in flight must not reach a half-wired page.
            if (c.lazy) c.lazy(bundle);
            if (bundle && c.lazy && !c.eager?.()) continue;      // armed only — nothing loads yet
            if (bundle) (injectedGroups[bundle] ||= []).push(c);
            else deferredComponents.push(c);                     // code already in main
        }

        // Start downloads now so they overlap the critical pass.
        for (const name in injectedGroups) loadBundle(name);
        loadIconTokens(mainCssLink());

        if (CONFIG.enableLogging) {
            const names = Object.keys(injectedGroups);
            const injected = names.reduce((n, name) => n + injectedGroups[name].length, 0);
            const total = criticalComponents.length + deferredComponents.length + injected;
            const detail = names.map((name) => `${name}:${injectedGroups[name].length}`);
            console.log(
                `[NDS] Initializing ${total}/${COMPONENTS.length} components ` +
                `(${criticalComponents.length} critical, ${deferredComponents.length} deferred` +
                `${detail.length ? ', ' + detail.join(', ') : ''})`
            );
        }

        initCriticalBatch();
        scheduleDebugAudits();
    }

    // enableLogging only: 3s after window load, so injected bundles have initialized and
    // icon masks are computable. Pulls nds-audit.min.js through the lazy stub.
    function scheduleDebugAudits() {
        if (!CONFIG.enableLogging) return;
        const run = () => setTimeout(() => NDS.Audit.run(), 3000);
        if (document.readyState === 'complete') run();
        else window.addEventListener('load', run, { once: true });
    }

    // window.NDSInitConfig wins over the <html> data-attributes.
    const rootEl = document.documentElement;
    const attrAutoInit = rootEl.getAttribute('data-nds-auto-init');
    const attrDisableAll = rootEl.getAttribute('data-nds-disable-all');
    const GLOBAL = window.NDSInitConfig || {};

    const CONFIG = {
        // Below ~40 keeps clear of TBT's 50ms long-task threshold on throttled CPUs.
        initBudgetMs: GLOBAL.initBudgetMs ?? 5,
        enableLogging: GLOBAL.enableLogging ?? false,
        enableTiming: GLOBAL.enableTiming ?? false,
        autoInitialize: GLOBAL.autoInitialize ?? (attrAutoInit != null ? attrAutoInit !== 'false' : true),
        disableAll: GLOBAL.disableAll ?? (attrDisableAll != null ? attrDisableAll === 'true' : false),
    };

    NDS.loadBundle = loadBundle;

    // "This container's contents changed." Walks the registry, so a component is
    // refreshed because it is REGISTERED, not because the caller remembered it.
    //   - owners (a `refresh` hook) drive the container from outside it; their hook runs
    //     INSTEAD of init and must claim surfaces that did not exist at load.
    //   - scanners re-run init(), idempotent via each component's sentinel.
    // The hook is a registry field, never a probe of NDS.X.refresh: Pagination's own
    // refresh() resets to page 1 and Empty's wants the element itself. Pagination and
    // Empty self-heal through their own observers, so they scan.
    // Server-driven lists are untouched: manual navs carry no auto stamp and AJAX filters
    // skip their refresh. Registry order holds: Selection recounts before Filter.
    // ponytail: scanners re-scan the whole document, the same cost as reinit(); give
    // them a scope argument only if a large page measures slow.
    function refreshContainer(container) {
        const root = container || document;
        for (const component of COMPONENTS) {
            const ns = NDS[component.name];
            if (!ns || ns.__ndsStub) continue;
            try {
                if (component.refresh) component.refresh(root);
                // matches() covers a root that IS the component (a panel pulled from a template).
                else if (!component.selector || root === document || root.matches?.(component.selector) || root.querySelector?.(component.selector)) component.init();
            } catch (error) {
                console.warn(`[NDS:refresh] ${component.name} failed:`, error);
            }
        }
    }

    // "This container is going away." Three shapes:
    //   1. backref convention: an `nds{Name}` instance on the element with a no-arg
    //      destroy() that also drops its stamps, so a later refresh() can re-claim it.
    //   2. `destroy(root)` hook: the component moved its elements out of root (Fab).
    //   3. `destroyEach`: no backref; NDS.X.destroy(el) per selector match. Declared,
    //      never probed — NDS.Slider.destroy() with no argument releases every slider.
    // Only what is INSIDE root is reached: pass the view's root, not the list.
    // ponytail: walks every element in the subtree (stamps have no prefix selector);
    // index instances only if a very large container measures slow.
    function destroyContainer(container) {
        const root = container || document;
        let destroyed = 0;
        for (const el of [root, ...root.querySelectorAll('*')]) {
            if (el.nodeType !== 1) continue;
            for (const key of Object.keys(el)) {
                // Backrefs only; sibling expandos hold flags with no destroy().
                if (!key.startsWith('nds') || typeof el[key]?.destroy !== 'function') continue;
                const instance = el[key];
                try {
                    instance.destroy();
                    destroyed++;
                    // Not every destroy() clears its backref; identity-guarded in case it re-initialized.
                    if (el[key] === instance) delete el[key];
                } catch (error) {
                    console.warn(`[NDS:destroy] ${key} failed:`, error);
                }
            }
        }
        for (const component of COMPONENTS) {
            const ns = NDS[component.name];
            if (!ns || ns.__ndsStub) continue;

            if (component.destroy) {
                try {
                    destroyed += component.destroy(root) || 0;
                } catch (error) {
                    console.warn(`[NDS:destroy] ${component.name} failed:`, error);
                }
                continue;
            }

            if (!component.destroyEach || typeof ns.destroy !== 'function') continue;
            const selector = component.destroySelector || component.selector;
            const owned = [...root.querySelectorAll(selector)];
            if (root.matches?.(selector)) owned.unshift(root);
            for (const el of owned) {
                // Count only a destroy that released a stamp (not one already released above,
                // never initialized, or stamped for paint alone).
                const stamps = () => el.getAttributeNames().filter((n) => n.startsWith('data-nds-') && n.endsWith('-initialized')).length;
                const before = stamps();
                try {
                    ns.destroy(el);
                    if (stamps() < before) destroyed++;
                } catch (error) {
                    console.warn(`[NDS:destroy] ${component.name} failed:`, error);
                }
            }
        }

        return destroyed;
    }

    // Markup built after detection: load only the bundles its own content needs, then
    // refresh. Loading every bundle would drag in audit, which must never auto-inject.
    function mountContainer(container) {
        const root = container || document;
        const needed = new Set();
        for (const c of COMPONENTS) {
            if (!c.selector) continue;
            const here = root.matches?.(c.selector) || root.querySelector?.(c.selector);
            const bundle = here && nsToBundle[c.name];
            if (bundle) needed.add(bundle);
        }
        return Promise.all([...needed].map(loadBundle)).then(() => refreshContainer(root));
    }

    NDS.Init = {
        initialize: initializeNDS,
        components: COMPONENTS,
        config: CONFIG,
        // Works regardless of enableLogging, which only controls the automatic sweep.
        audit: () => NDS.Audit.run(),
        refresh: refreshContainer,
        mount: mountContainer,
        destroy: destroyContainer,
    };

    // Not DOMContentLoaded: DCL also waits for every OTHER defer script, which would let
    // them gate the reveal. Main is a defer script, so the DOM is parsed here already;
    // only the rare sync-in-<head> case waits.
    if (CONFIG.autoInitialize) {
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', initializeNDS);
        } else {
            setTimeout(initializeNDS, 0);
        }
    }
})();
