/* NDS.Init — public surface
 * Rides: (none — this is the orchestrator every component registers with)
 * Methods:
 *   NDS.Init.initialize()      run the full init pass (called automatically on DOM ready)
 *   NDS.Init.components        the component registry: {name, selector, init, critical}
 *   NDS.Init.config            the resolved config
 *   NDS.Init.audit()           run the debug audits by hand (unregistered inline icons,
 *                              unclaimed filter and paged containers)
 *   NDS.loadBundle(name)       load one injected bundle on demand, then call that
 *                              component's init() → Promise
 *   NDS.loadExtras()           back-compat shim for loadBundle('extras')
 * Events:
 *   (none)
 * Hooks (window globals — set these BEFORE the bundle loads):
 *   window.NDSInitConfig   {autoInitialize, disableAll, enableLogging, enableTiming}
 *   window.NDSAssetBase    override the directory the injected bundles load from
 *   window.__NDS_BUNDLES   the build-generated bundle manifest — never hand-write it
 *   written by the loader: data-nds-loaded on <html> — the reveal stamp, set once the
 *                          main CSS has applied
 * Gotchas:
 *   - Three bundles. nds-main.min.js is a defer script and GATES the page reveal; the
 *     delegated and extras bundles are injected after the reveal and never gate anything.
 *   - A component whose bundle has not arrived still answers: the loader installs a lazy
 *     stub, so NDS.X.method() triggers the load instead of throwing.
 *   - After injecting content, prefer that component's own reinit() over
 *     NDS.Init.initialize() — the full pass re-sweeps the whole page.
 *   - Bundle membership is generated by the build. Never hardcode it in JS.
 */
// NDS Unified Initialization System
(() => {
    'use strict';

    // Component registry. Array order = init order WITHIN each tier — the
    // partition (see initializeNDS) splits this list into critical / deferred /
    // per-injected-bundle buckets that run in sequence: critical batches →
    // deferred idle drain → each bundle's group on arrival. Reordering changes
    // order only among same-tier components.
    //
    // Standard component API contract:
    //   Factory components (per-element):  init(), reinit(), create(el)
    //   Singleton components (one global): init() + component-specific methods
    //   Utility/API components:            init() + utility methods
    //
    // All components live under the NDS.* namespace (e.g. NDS.Modal, NDS.Accordion)
    // Form sub-systems are grouped: NDS.Forms, NDS.Upload, NDS.OTP
    // Core utilities: NDS.Theme, NDS.debounce, NDS.onDOMAdd, etc.
    // Pre-boot window globals (set before this bundle loads, so they live on
    // window, not NDS): window.NDSInitConfig (init config), window.NDSAssetBase
    // (asset-dir override), window.__NDS_BUNDLES (build-generated bundle manifest).
    const COMPONENTS = [
        {
            name: 'Mainnav',
            selector: '.nds-main-nav',
            init: () => NDS.Mainnav?.init?.(),
        },
        {
            // Deferred: the saved theme is stamped pre-paint by the inline FOUC
            // script (head-inline-scripts.html) and critical-inline CSS paints the
            // [data-theme="dark"] body/hero bg, so first paint is correct with no JS.
            // init() only syncs toggle-widget UI (icon/checkbox/aria) and wires the
            // toggle — no page-color repaint; theme application fires on interaction.
            name: 'Theme',
            selector: '[data-theme-toggle], #ndsThemeToggle, [data-theme-value]',
            init: () => NDS.Theme?.init?.(),
        },
        {
            // Critical: init un-hides [hidden] FOUC-guard form wrappers and reveals
            // the .nds-clear button on pre-filled fields — first-paint writes that
            // CLS if deferred (forms have no own skeleton; the content-layout gate
            // hides them until reveal). Init is cold (no layout reads).
            name: 'Forms',
            selector: '.nds-form-control',
            init: () => NDS.Forms?.init?.(),
            critical: true,
        },
        {
            // Deferred but stays in MAIN (no bundle): init() restores pre-selected
            // labels, which are JS-derived from the option text. A delegated/extras
            // bundle loads after the critical pass, so a pre-filled select would flash
            // empty until then on slow links — keep the code in main so the restore
            // runs on the local idle pass. Each select's NDS.Dropmenu builds lazily
            // on first focusin; forms doesn't reach in, so no critical→deferred dependency.
            name: 'CustomSelect',
            selector: '.nds-select-input',
            init: () => NDS.CustomSelect?.init?.(),
        },
        {
            // Deferred: input wiring fires on user typing — no first-paint
            // visual. The input[autofocus] restore is opt-in; pages that
            // ship autofocus on an OTP input will see the restore delayed
            // by one idle slot. Acceptable for the common case.
            name: 'OTP',
            selector: '.nds-otp-group',
            init: () => NDS.OTP?.init?.(),
        },
        {
            // Deferred: rule chips are server-rendered at data-status="neutral"
            // (matches empty state — no CLS), and validity is only consulted at
            // submit. Ships in the delegated bundle — init's check() recomputes
            // from the current value, so keystrokes in the pre-bundle gap recover.
            name: 'Password',
            selector: '.nds-form-container.nds-password',
            init: () => NDS.Password?.init?.(),
        },
        {
            name: 'Tabs',
            selector: '.nds-tabs',
            init: () => NDS.Tabs?.init?.(),
        },
        {
            // Deferred: init reparents the table into .nds-table-wrapper (the
            // overflow-x scroll container) + wires sort/select. The reparent is
            // layout-neutral (wrapper adds overflow only, no box-size change), so
            // it forces no reflow and measured ~0 CLS in the delegated bundle —
            // safe to load late. Sort/select clicks in the pre-bundle gap no-op
            // and recover on the next click.
            name: 'Tables',
            selector: '.nds-table',
            init: () => NDS.Tables?.init?.(),
        },
        {
            // Deferred: default-open panels now ship data-state="open" in markup
            // (button + collapse), so CSS paints them expanded with no JS — the
            // :not([data-nds-accordion-initialized]) rule suppresses the load
            // transition, so there's no collapsed→open animation or CLS. init()
            // only reconciles state + wires clicks; rides the delegated bundle.
            // Header clicks in the pre-bundle gap no-op and recover on the next click.
            name: 'Accordion',
            selector: '.nds-accordion',
            init: () => NDS.Accordion?.init?.(),
        },
        {
            // Delegated: pre-init paint is CSS-owned, keyed on the stepper's
            // OWN stamp (_stepper.scss skeleton: title/description bars +
            // circle fills; radial force-shows its first step, which would
            // otherwise paint EMPTY without JS data-state stamping). Init
            // landing after the reveal swaps placeholders for the stamped
            // states in place. Showcase's setFallback/getFallback calls are
            // interaction-time — the delegated bundle is long loaded by then.
            name: 'Stepper',
            selector: '.nds-stepper',
            init: () => NDS.Stepper?.init?.(),
        },
        {
            // Delegated: pre-init paint is CSS-owned, keyed on the swiper's
            // OWN stamp (crit: hero collapses to slide 1; non-hero pins a
            // clipped card-width slide row; _swiper.scss reserves the
            // [hidden] nav row) — so init landing after the reveal releases
            // into reserved space, no track re-expansion. Hero LCP is the
            // slide-1 image, painted from markup regardless of JS. The
            // foundation-day slide injector handles the init race in both
            // directions (reinit only after the stamp).
            name: 'Swiper',
            selector: '.nds-swiper',
            init: () => NDS.Swiper?.init?.(),
        },
        {
            name: 'Upload',
            selector: '.nds-file-upload',
            init: () => NDS.Upload?.init?.(),
        },
        {
            // Deferred + self-contained: the Web Speech engine + button live in
            // nds-voice-input.js, consumed by nothing else. Interaction-driven
            // (recognition starts on click), so a late wire lands before the click.
            name: 'VoiceInput',
            selector: '.nds-voice-input',
            init: () => NDS.VoiceInput?.init?.(),
        },
        {
            // Critical: init un-hides the [hidden] mobile toggle and fills its
            // collapsed label from the server-rendered active item. Deferral = toggle
            // CLS + a hidden nav affordance until the idle pass.
            name: 'Sidemenu',
            selector: '.nds-sidemenu',
            init: () => NDS.Sidemenu?.init?.(),
            critical: true,
        },
        {
            // Critical: the hero-aside variant paints the panel at a -180px
            // placeholder (--nds-sideinfo-top fallback); init's first updatePosition
            // writes the measured hero-head offset. Deferral lands that correction
            // post-reveal = vertical jump of an above-the-fold aside (CLS). Cold-init
            // (first measure rides the onElementResize initial callback).
            name: 'Sideinfo',
            selector: '.nds-sideinfo',
            init: () => NDS.Sideinfo?.init?.(),
            critical: true,
        },
        {
            // Critical: initActiveStates expands the active-page path at init so
            // the current page is visible without a manual expand (ease of
            // use). The server marks the active leaf but paints its ancestors
            // collapsed, so deferral would pop the path open post-paint
            // (CLS) and hide the active item. Init is cold (no layout reads).
            name: 'Drawer',
            selector: '.nds-drawer',
            init: () => NDS.Drawer?.init?.(),
            critical: true,
        },
        {
            // Critical: data-toc-source TOCs build their list from page headings at
            // init (populate → replaceChildren), a structural height change that
            // CLSs if it lands after the critical pass — and the list count is
            // arbitrary, so no CSS skeleton can reserve the slot. Ships in main so
            // it wires in the first burst; init does no layout reads (the measuring
            // pass is deferred to onIdle), so it adds no forced reflow.
            name: 'Toc',
            selector: '.nds-toc',
            init: () => NDS.Toc?.init?.(),
            critical: true,
        },
        {
            // Critical: the overflow affordance (has-more edge-mask + sticky
            // show-more button) is applied via the onElementResize initial
            // callback, which the critical pass front-loads. Deferral would pop
            // it in post-reveal (CLS) for above-the-fold overflow content (e.g.
            // tab bars in nds-tabs). Init is cold — no synchronous layout reads
            // (the first measure runs in the ResizeObserver callback).
            name: 'ScrollMore',
            selector: '.nds-scroll-more',
            init: () => NDS.ScrollMore?.init?.(),
            critical: true,
        },
        {
            // Deferred: progress animations are cosmetic on-scroll work.
            name: 'Progress',
            selector: '.nds-progress-circle, .nds-progress-bar',
            init: () => NDS.Progress?.init?.(),
        },
        {
            // Deferred: counter animations are cosmetic on-scroll work.
            name: 'Numbers',
            selector: '.nds-number-format, .nds-counter-value',
            init: () => NDS.Numbers?.init?.(),
        },
        {
            // Documentation-only highlighter, so it rides extras and never gates the
            // reveal — consumer sites render no code blocks and fetch nothing.
            // Delegate-safe: _code.scss paints the box, reserves the line-number
            // gutter and colours inline code with no JS at all, so a late init adds
            // only token colour + line digits and can't shift layout.
            // `.nds-code` alone is enough: every .code-example is a tab panel inside
            // it, and inline code needs no JS. Avoids bare `code` so detection
            // doesn't sweep every <code> on docs pages.
            name: 'Code',
            selector: '.nds-code',
            init: () => NDS.Code?.init?.(),
        },
        {
            name: 'Copy',
            selector: '.nds-copy',
            init: () => NDS.Copy?.init?.(),
        },
        // Note: showcase is intentionally NOT registered here. Like accessibility,
        // it ships as its own defer bundle (nds-showcase.min.js) and self-boots.
        // The loader's init is decoupled from DOMContentLoaded, so registering it
        // would risk init() running before that sibling bundle has executed.
        {
            name: 'Selection',
            selector: '[data-selection-target]',
            init: () => NDS.Selection?.init?.(),
        },
        {
            name: 'Share',
            selector: '.nds-share',
            init: () => NDS.Share?.init?.(),
        },
        {
            // Detection-only: presence of a [data-export] button loads the
            // extras bundle; export's init wires the delegated click handler.
            name: 'Export',
            selector: '[data-export]',
            init: () => NDS.Export?.init?.(),
        },
        {
            name: 'DatePicker',
            selector: '.nds-date-input',
            init: () => NDS.DatePicker?.init?.(),
        },
        {
            name: 'FontLoading',
            selector: null,
            init: () => NDS.FontLoading?.init?.(),
            universal: true,
        },
        {
            // Critical: NDS.Link.init() tags external links with no layout reads
            // (guards are hostname/classList only), so it forces no reflow and is
            // safe before first paint — above-the-fold external badges are present
            // on the first frame (no pop-in CLS). NOTE: keep it layout-read-free;
            // an earlier getBoundingClientRect viewport-partition forced a full
            // page layout here (~110ms@6.6x on index) and had to be removed.
            name: 'Link',
            selector: null,
            init: () => NDS.Link?.init?.(),
            universal: true,
            critical: true,
        },
        {
            name: 'Cookies',
            selector: '#ndsCookiesAcceptBtn',
            init: () => NDS.Cookies?.init?.(),
        },
        {
            // Deferred + self-contained: nothing consumes NDS.Rating and the stars
            // paint from markup/CSS — click-to-rate wiring lands before interaction.
            name: 'Rating',
            selector: '.nds-rating',
            init: () => NDS.Rating?.init?.(),
        },
        {
            // Deferred: native <input type="range"> is interactive and a11y-correct
            // with no JS — init only paints the gradient fill (CSS var) and updates
            // the value <output>. Clicks/drags in the pre-bundle gap update value
            // natively; the fill repaints on the first `input` after the delegated
            // bundle lands.
            name: 'Slider',
            selector: '.nds-slider',
            init: () => NDS.Slider?.init?.(),
        },
        {
            // Deferred: the collapsed clamp is pure CSS (_utilities.scss base
            // max-height/overflow, server-rendered + in main), so the box paints
            // correctly with no JS. init() is registration-only; the height read +
            // "show more" button + 'expandable' stamp run from the ResizeObserver's
            // first delivery (post-reveal in either tier) and are layout-neutral
            // (absolute button + paint-only mask) — no expand↔collapse height swap.
            name: 'Expandable',
            selector: '.nds-expandable',
            init: () => NDS.Expandable?.init?.(),
        },
        {
            // Delegated: pre-init paint is CSS-owned, keyed on the breadcrumb's
            // OWN stamp — crit shapes 6+ trails to the post-collapse geometry
            // (first + 40px ellipsis stand-in + last two), main bars the labels,
            // so init landing after the reveal swaps in place (verified box-
            // identical). The ellipsis dropdown uses Dropmenu from main —
            // present long before this drains.
            name: 'Breadcrumb',
            selector: '.nds-breadcrumb-nav',
            init: () => NDS.Breadcrumb?.init?.(),
        },
        {
            name: 'Dropmenu',
            selector: '.nds-dropmenu',
            init: () => NDS.Dropmenu?.init?.(),
        },
        {
            name: 'Tooltip',
            selector: '.nds-tooltip',
            init: () => NDS.Tooltip?.init?.(),
        },
        {
            // Critical: pre-selected chips are JS-built at init (server markup
            // ships the chip track empty) and grow the field height, which has
            // no reserved space in CSS — deferral would inject them post-reveal
            // (CLS). The empty case is stable, but registration can't know which.
            name: 'Multiselect',
            selector: '.nds-multiselect',
            init: () => NDS.Multiselect?.init?.(),
            critical: true,
        },
        {
            // Critical twice over: restored chips are JS-built at init (CLS
            // if deferred, like Multiselect), AND typing is the primary
            // interaction — in a pre-bundle gap Enter native-submits the
            // form (destructive, not a recoverable no-op; the OTP rule).
            // Stays eager even if the chips ever become server-rendered.
            name: 'TagInput',
            selector: '.nds-taginput',
            init: () => NDS.TagInput?.init?.(),
            critical: true,
        },
        {
            // Deferred: results fetch on user typing — no first-paint visual.
            name: 'Autocomplete',
            selector: '.nds-form-container[data-url]',
            init: () => NDS.Autocomplete?.init?.(),
        },
        {
            // Deferred: adopts a standard textarea field at init — editable and
            // toolbar are generated (data-editor-toolbar); the pre-init skeleton
            // in _editor.scss holds the field until the stamp lands.
            name: 'Editor',
            selector: '.nds-editor',
            init: () => NDS.Editor?.init?.(),
        },
        {
            // Delegated: crit CSS holds each filter target container
            // ([data-filter-items]) hidden until init stamps
            // data-nds-filter-initialized on it — the data-nds-loaded pattern,
            // per container — so a URL-active filter (?name=value) never
            // flashes the unfiltered list: the stamp lands after
            // applyUrlParams() has settled the filtered state. Registered
            // BEFORE Pagination — drainList inits in registry order, so
            // applyUrlParams() stamps data-filtered before Pagination's
            // filter-aware item read, same invariant as the old critical pass.
            // Gate on [data-filter-target] (not .nds-filter): a filter is defined
            // by its target link, so it must init even when there's no .nds-filter
            // dropdown (e.g. a search-only filter).
            name: 'Filter',
            selector: '[data-filter-target]',
            init: () => NDS.Filter?.init?.(),
        },
        {
            // Delegated: pre-init paint is covered by CSS — the
            // data-paged-initialized skeleton (crit) shows the first 5 items —
            // readPerPage's default, so a container that sets no --per-page has
            // no boundary shift at all — and collapses table rows, and
            // _pagination.scss reserves the empty nav's row height, so init
            // landing after the reveal inserts the list without shifting
            // content. Bounded known shifts: --per-page ≠ 5; manual >5-page
            // lists collapse to the ellipsis post-reveal. Registered AFTER Filter so
            // a URL-active filter has stamped data-filtered before this paint;
            // Filter's refresh call during its init lands before this nav's
            // setup and is skipped (refreshAutoPagination's pre-init guard).
            name: 'Pagination',
            selector: '.nds-pagination',
            init: () => { NDS.Pagination?.init?.(); NDS.Pagination?.initAuto?.(); },
        },
        {
            name: 'Ipv',
            selector: '.nds-ipv-thumbnail',
            init: () => NDS.Ipv?.init?.(),
        },
        {
            name: 'Modal',
            selector: '.nds-modal',
            init: () => NDS.Modal?.init?.(),
        },
        {
            name: 'Alert',
            selector: '.nds-alert',
            init: () => NDS.Alert?.init?.(),
        },
        {
            // Delegated: the panel ships [hidden], so markup + CSS paint it
            // correctly with the JS deleted — zero first paint, zero CLS.
            // Toggle clicks in the pre-bundle gap no-op and recover on the
            // next click (the Tabs/Tables/Accordion precedent).
            name: 'Panel',
            selector: '.nds-panel',
            init: () => NDS.Panel?.init?.(),
        },
        {
            name: 'UserFeedback',
            selector: '.nds-user-feedback',
            init: () => NDS.UserFeedback?.init?.(),
        },
        {
            name: 'Chart',
            selector: '.nds-chart',
            init: () => NDS.Chart?.init?.(),
        },
        {
            // Critical: init() BUILDS the placeholder DOM (icon + message) into empty
            // containers — it isn't server-rendered. Deferral injects it post-reveal = CLS.
            name: 'Empty',
            selector: '.nds-empty',
            init: () => NDS.Empty?.init?.(),
            critical: true,
        },
        {
            // Critical: enforces single-submit. A click in the deferred gap would
            // bypass the cooldown.
            name: 'CooldownButton',
            selector: '.nds-cooldown',
            init: () => NDS.CooldownButton?.init?.(),
            critical: true,
        },
        {
            // Delegated: routing moves each .nds-fab into its edge dock. A FAB is
            // non-critical chrome, so it rides the delegated bundle alongside the
            // panels it toggles (both appear together — no visible-but-dead FAB in
            // the pre-panel gap). Pre-route flash is prevented by the FAB's own
            // `hidden` attribute (the universal [hidden] rule in _fold.scss);
            // register() strips it once docked. Cold init — appendChild plus
            // pooled observers, no layout reads.
            name: 'Fab',
            selector: '.nds-fab, .nds-fab-dock',
            init: () => NDS.Fab?.init?.(),
        },
        // Topbar widgets — placed last because they're non-critical chrome
        // (digital stamp, clock, hijri date, weather, city). Their updates are
        // interaction- or network-bound anyway; ordering them after interactive
        // components (modal, tooltip, filter, pagination…) keeps the early init
        // chain focused on what the user can click.
        {
            // Standalone trust-banner disclosure. First paint is correct with JS
            // deleted (panel ships [hidden]; CSS owns the expand), so it rides the
            // delegated bundle. Decoupled from Mainnav — mutual exclusion with the
            // nav comes from each surface's own outside-click handler.
            name: 'DigitalStamp',
            selector: '.nds-digitalStamp-tab',
            init: () => NDS.DigitalStamp?.init?.(),
        },
        {
            name: 'CityWeather',
            selector: '#nds-weatherInfo, #nds-cityName',
            init: () => NDS.CityWeather?.init?.(),
        },
        {
            name: 'TimeDate',
            selector: '#nds-date, #nds-realTimeClock',
            init: () => NDS.TimeDate?.init?.(),
        },
        // Note: accessibility is intentionally NOT registered here. The
        // optional assets/js/nds-accessibility.min.js bundle self-boots via
        // its own IIFE — arms on localStorage-saved prefs (apply on load) or
        // on FAB click (lazy init). Loader has zero references; the bundle
        // can be omitted entirely without touching core.
    ];

    // Cross-batch yielding. Prefers scheduler.yield() (Chrome 129+) so the
    // browser can preempt for input/paint between batches; falls back to a
    // shared MessageChannel — allocated once per page lifetime instead of
    // per initializeNDS() call so reinit-heavy consumers (SPA route changes)
    // don't leak channels. FIFO queue handles overlapping init chains
    // (reinit fired while a previous chain is still draining).
    const _yieldChannel = new MessageChannel();
    const _yieldQueue = [];
    _yieldChannel.port1.onmessage = () => {
        const cb = _yieldQueue.shift();
        if (cb) cb();
    };
    const yieldToBrowser = (typeof scheduler !== 'undefined' && scheduler.yield)
        ? (cb) => scheduler.yield().then(cb)
        : (cb) => { _yieldQueue.push(cb); _yieldChannel.port2.postMessage(null); };

    // rIC fallback for older Safari (<18). Deadline counts down a real 5ms
    // slot so drainList yields like native rIC instead of running every
    // idle component in one macrotask. Fidelity gap: unlike native rIC this
    // fires ~immediately (setTimeout 1ms), NOT at true idle — so on those
    // engines deferred components init right after the critical pass, competing with
    // the post-load window (the 5ms slot still caps each task). The {timeout}
    // arg is ignored (didTimeout stays false): setTimeout always fires, so no
    // timeout-forced run is needed.
    const scheduleIdle = window.requestIdleCallback ||
        ((cb) => {
            const start = performance.now();
            setTimeout(() => cb({
                didTimeout: false,
                timeRemaining: () => Math.max(0, 5 - (performance.now() - start))
            }), 1);
        });

    // Asset base + version derived from the loader's own <script>. nds-loader.js
    // is bundled last into nds-main.min.js, so during this IIFE's synchronous
    // eval document.currentScript IS the main bundle's element. Captured here at
    // eval time — currentScript is null inside the async callbacks below. Sibling
    // bundles reuse main's origin (so they pass a consumer's CSP 'self'/host
    // allowlist for free — no new origin) and its ?ver= cache-bust. Fallbacks:
    // find the main script by src, then a window.NDSAssetBase override.
    const SELF = document.currentScript ||
        [...document.scripts].find((s) => /nds-main(\.min)?\.js/.test(s.src));
    const ASSET = (() => {
        if (SELF && SELF.src) {
            const u = new URL(SELF.src, location.href);
            return { dir: u.href.slice(0, u.href.lastIndexOf('/') + 1), ver: u.search };
        }
        return { dir: window.NDSAssetBase || '', ver: '' };
    })();
    const bundleUrl = (file) => ASSET.dir + file + ASSET.ver;

    // Injected (non-main) bundles + the namespaces each ships, generated by the
    // build from the actual bundle file lists and prepended to this bundle as
    // window.__NDS_BUNDLES = { delegated: { file, ns:[...] }, extras: {...} }.
    // Bundle membership (location) is owned entirely by the build — the loader and
    // the component registry never hardcode it. Each injected bundle loads after
    // the critical pass (never a render-blocking <script defer>), so its download
    // never gates the reveal.
    const MAP = window.__NDS_BUNDLES || {};
    // namespace → bundle name, for the lazy stubs + the partition's location lookup.
    const nsToBundle = {};
    for (const b in MAP) for (const ns of (MAP[b].ns || [])) nsToBundle[ns] = b;

    // Trusted Types passthrough for script.src — a TrustedScriptURL sink when
    // require-trusted-types-for 'script' is enforced and no default policy exists.
    // Same-origin, known filenames only. try/catch: a consumer's trusted-types
    // directive may not allowlist this policy name (then we fall back to a string,
    // which their default policy handles, or the assignment throws and the bundle
    // is simply skipped — inits no-op via ?.).
    let _ttPolicy;
    if (window.trustedTypes && trustedTypes.createPolicy) {
        try {
            _ttPolicy = trustedTypes.createPolicy('nds', { createScriptURL: (u) => u });
        } catch (e) { /* policy name not allowed — fall back to plain string */ }
    }

    // Loads an injected bundle once and resolves when it's ready. Idempotent —
    // returns the in-flight/settled promise on repeat calls, so the auto-load
    // (when a present component needs it, see below) and the public
    // NDS.loadBundle() (for content injected after load) share one fetch.
    // Resolves on load OR error so callers never hang; a missing/blocked bundle
    // leaves inits as ?. no-ops. Skips injection when a <script> for the bundle
    // already exists — a consumer under a no-injection CSP can self-host it with
    // their own nonce/integrity and the loader still drives init. Propagates
    // main's nonce so it passes nonce-only policies without 'strict-dynamic'.
    // Usage for dynamic content: await NDS.loadBundle('extras'); NDS.Chart.init();
    const _bundlePromises = {};
    function loadBundle(name) {
        if (_bundlePromises[name]) return _bundlePromises[name];
        const file = MAP[name] && MAP[name].file;
        if (!file || !ASSET.dir) return (_bundlePromises[name] = Promise.resolve());
        if ([...document.scripts].some((s) => s.src && s.src.includes(file))) {
            return (_bundlePromises[name] = Promise.resolve());
        }
        _bundlePromises[name] = new Promise((resolve) => {
            const url = bundleUrl(file);
            const s = document.createElement('script');
            s.src = _ttPolicy ? _ttPolicy.createScriptURL(url) : url;
            s.fetchPriority = 'low';
            if (SELF && SELF.nonce) s.nonce = SELF.nonce;
            s.onload = resolve;
            s.onerror = () => {
                console.warn(`[NDS] bundle '${name}' failed to load (${url})`);
                // Remove the failed <script> + drop the cache so a later loadBundle()/lazy-stub call can retry a transient failure (else the present-script guard above short-circuits re-injection on the lingering failed element).
                s.remove();
                delete _bundlePromises[name];
                resolve();
            };
            // Body, not head: injection happens post-reveal, so the DOM is parsed
            // and a body-tail script is where a deferred bundle belongs. Falls back
            // to head for the sync-in-<head> case, where body doesn't exist yet.
            (document.body || document.head).appendChild(s);
        });
        return _bundlePromises[name];
    }

    // Transparent lazy stubs: expose each injected namespace BEFORE its bundle
    // loads, so existing public usage (e.g. NDS.Chart.create(...)) keeps working
    // unchanged — the call triggers the right bundle (resolved from the build
    // manifest; nothing is hardcoded in consumer code) and runs once it's ready.
    // The bundle overwrites the stub when it executes, so every post-load call is
    // the native, synchronous object; the stub only bridges calls made before the
    // bundle arrives. A method invoked while stubbed returns a Promise (resolves
    // after load) — fine for fire-and-forget calls. If the bundle is missing the
    // call no-ops with a warning (the __ndsStub guard stops it recursing).
    // LIMIT: the stub bridges fire-and-forget METHOD CALLS only — a synchronous
    // read (a property value, or a boolean-returning call used in a condition
    // like `if (NDS.X.isActive())`) gets the always-truthy stub function/Promise
    // during the pre-bundle gap and silently takes the wrong branch. A component
    // whose API is read synchronously by main-bundle code (e.g. mainnav reads
    // NDS.Backdrop.isActive()) must therefore stay in main, not be delegated.
    for (const ns in nsToBundle) {
        if (NDS[ns]) continue;
        const bundle = nsToBundle[ns];
        NDS[ns] = new Proxy({ __ndsStub: true }, {
            get(target, prop) {
                if (prop === '__ndsStub') return true;
                if (prop === 'then' || typeof prop === 'symbol') return undefined;
                return (...args) => loadBundle(bundle).then(() => {
                    const real = NDS[ns];
                    if (real && !real.__ndsStub && typeof real[prop] === 'function') {
                        return real[prop](...args);
                    }
                    // Two distinct failures: the bundle landed but the namespace has
                    // no such method (caller error — name the real surface), vs the
                    // bundle never arrived. The old single message blamed the bundle
                    // for both, sending consumers down the wrong path.
                    if (real && !real.__ndsStub) {
                        console.warn(`[NDS] ${ns}.${String(prop)} is not a method of NDS.${ns} — its surface: ${Object.keys(real).join(', ')}`);
                    } else {
                        console.warn(`[NDS] ${ns}.${String(prop)}() unavailable — bundle '${bundle}' missing`);
                    }
                });
            },
        });
    }

    function initializeNDS() {
        if (CONFIG.disableAll === true) {
            if (CONFIG.enableLogging) {
                console.warn('[NDS] Initialization disabled (config.disableAll = true)');
            }
            return;
        }
        const startTime = performance.now();

        // Partition buckets. The init-loop closures capture these bindings; all
        // are assigned (below) before initCriticalBatch runs. Injected-bundle
        // groups init in their own pass once each bundle loads — see
        // initCriticalBatch.
        let criticalComponents, deferredComponents, injectedGroups;

        const runInit = (component) => {
            const start = CONFIG.enableTiming ? performance.now() : 0;
            try {
                component.init();
                if (CONFIG.enableLogging) {
                    const timing = CONFIG.enableTiming
                        ? ` ${(performance.now() - start).toFixed(1)}ms`
                        : '';
                    console.log(`[NDS:init] ${component.name}${timing}`);
                }
            } catch (error) {
                console.warn(`[NDS:init] ${component.name} failed:`, error);
            }
        };

        // Stamp data-nds-loaded — the reveal — only once main CSS has applied.
        // The reveal rules are main-gated, so nothing paints before then; pinning
        // the stamp to main keeps data-nds-loaded honest ("styled + inited"), and
        // lets _section.scss gate off-screen content-visibility on
        // :not([data-nds-loaded]) (cv covers the reveal layout, drops at the
        // stamp) and the scroll restore key off the same signal — no extra flag.
        // main.css is the deferred <link>; .sheet is set once applied, else wait
        // for its load. window.load is the backstop so the reveal can't hang.
        function stampWhenStyled() {
            const root = document.documentElement;
            // Marker first, filename second. The marker sits on the stylesheet link
            // the head script injected (the script moves it off the preload, which
            // never gets a `.sheet`). The filename fallback keeps a pre-1.7 head —
            // and anyone fingerprinting their asset names — working. Two queries,
            // not a comma list: a comma list resolves by document order, and the
            // main CSS preload (same filename, earlier in head) would win.
            const main = document.querySelector('link[data-nds-defer="main"]')
                || document.querySelector('link[href*="nds-main.min.css"]');
            // Idempotent: three listeners race to get here and only one may inject.
            const done = () => {
                if (root.hasAttribute('data-nds-loaded')) return;
                root.setAttribute('data-nds-loaded', '');
                loadIconSheets(main);
            };
            // Already applied? `.sheet` is set once the CSSOM attaches. Catching this
            // here matters: a load event that already fired before these listeners
            // attach must not strand the reveal on the window.load backstop, which
            // waits on every subresource — images, fonts, iframes.
            if (!main || main.sheet) { done(); return; }
            main.addEventListener('load', done, { once: true });
            main.addEventListener('error', done, { once: true });
            window.addEventListener('load', done, { once: true });
        }

        // Icon sheets ride behind main CSS so they never compete inside the LCP
        // window. They load from here rather than an inline head script so a strict
        // CSP needs no extra grant: this bundle is already an allowed origin, while
        // an inline script needs the consumer's nonce or hash. The href comes off the
        // main CSS link — same folder as the icon sheets in every build — not off the
        // JS directory, which a consumer's bundler may place somewhere else entirely.
        function loadIconSheets(main) {
            if (!main) return;
            const href = (name) => main.href.replace('nds-main.min.css', name);
            // Per-sheet dedupe: skip a sheet the head already carries (self-hosting
            // consumer, or a pre-1.7 inline head that adds its own). Check link
            // elements, not document.styleSheets — a sheet still downloading has no
            // entry there yet, and missing it would inject a duplicate.
            const add = (url) => {
                if ([...document.querySelectorAll('link[rel="stylesheet"]')].some((l) => l.href === url)) return null;
                const l = document.createElement('link');
                l.rel = 'stylesheet';
                l.href = url;
                document.head.appendChild(l);
                return l;
            };
            const icons = add(href('nds-icons.min.css'));
            // The stamp gates icon opacity (_sass/_icons.scss) — without it they stay invisible.
            if (icons) icons.onload = () =>
                document.documentElement.setAttribute('data-nds-icons-loaded', '');
            add(href('hgi-rounded-stroke-min.css'));
        }

        // Critical pass (the reveal checklist): time-sliced. Small inits share a
        // task; a heavy init lands alone. Yields when the per-batch budget is
        // exceeded.
        let criticalIndex = 0;
        function initCriticalBatch() {
            const batchStart = performance.now();
            while (
                criticalIndex < criticalComponents.length &&
                performance.now() - batchStart < CONFIG.initBudgetMs
            ) {
                runInit(criticalComponents[criticalIndex++]);
            }
            if (criticalIndex < criticalComponents.length) {
                yieldToBrowser(initCriticalBatch);
            } else {
                // Checklist complete. Deferred components whose code is already in
                // main drain in idle slots immediately — never gated on an
                // injected-bundle fetch (or on the reveal stamp below).
                if (deferredComponents.length) drainList(deferredComponents, logAllDone);
                else logAllDone();

                // Injected-bundle components init in their own pass once that
                // bundle arrives, so a (low-priority) download never delays the
                // main idle drain above. loadBundle resolves on load OR error
                // (missing/blocked bundle → inits no-op via ?.).
                for (const name in injectedGroups) {
                    const group = injectedGroups[name];
                    loadBundle(name).then(() => drainList(group));
                }

                // Hand the critical-CSS skeletons off to the now-styled
                // components — but only once main CSS has actually applied.
                stampWhenStyled();
            }
        }

        // Idle-slot drain: runs a component list across idle slots, as many as
        // fit each slot. Self-schedules until the list is exhausted; the timeout
        // ensures it still runs if the page never goes idle. Shared by the
        // deferred list and each injected-bundle group (each gets its own index/onDone).
        function drainList(list, onDone) {
            let i = 0;
            function drain(deadline) {
                while (
                    i < list.length &&
                    (deadline.didTimeout || deadline.timeRemaining() > 1)
                ) {
                    runInit(list[i++]);
                }
                if (i < list.length) scheduleIdle(drain, { timeout: 2000 });
                else if (onDone) onDone();
            }
            scheduleIdle(drain, { timeout: 2000 });
        }

        function logAllDone() {
            if (CONFIG.enableTiming) {
                console.log(
                    `[NDS] All components initialized in ${Math.round(performance.now() - startTime)}ms`
                );
            }
        }

        // Run detection + the critical pass directly — no rAF. The page is CSS-
        // hidden behind the critical-CSS skeleton until the critical pass stamps
        // data-nds-loaded, so there's nothing visible to protect with a pre-
        // paint frame: the rAF only pushed the reveal back a frame and froze
        // init entirely in a hidden tab (rAF never fires for a hidden document,
        // so a background-opened tab would never initialize). We already run off
        // the eval/DCL task via the setTimeout(0) kickoff below; detection's
        // per-component querySelector (fast path: short-circuits at first match)
        // joins the first critical batch's wall clock.
        // Source order (registry above) is priority order; push preserves it.
        criticalComponents = [];
        deferredComponents = [];
        injectedGroups = {};
        for (const c of COMPONENTS) {
            const present = c.universal || (c.selector && document.querySelector(c.selector));
            if (!present) continue;
            if (c.critical) {
                criticalComponents.push(c);                          // on the checklist → ships in main
                continue;
            }
            const bundle = nsToBundle[c.name];                   // location from the build manifest
            if (bundle) (injectedGroups[bundle] ||= []).push(c); // deferred → injected bundle
            else deferredComponents.push(c);                     // deferred → already in main
        }

        // Kick off each needed bundle now so its (low-priority) download
        // overlaps the critical pass. loadBundle is idempotent; its components
        // init in a per-bundle pass once it lands (see initCriticalBatch) — the
        // fetch never gates the reveal.
        for (const name in injectedGroups) loadBundle(name);

        if (CONFIG.enableLogging) {
            const names = Object.keys(injectedGroups);
            const injected = names.reduce((n, name) => n + injectedGroups[name].length, 0);
            const total = criticalComponents.length + deferredComponents.length + injected;
            const detail = names.map((name) => `${name}:${injectedGroups[name].length}`);
            console.log(
                `[NDS] Initializing ${total}/${COMPONENTS.length} components ` +
                `(${criticalComponents.length} critical, ${deferredComponents.length} deferred` +
                `${detail.length ? ', ' + detail.join(', ') : ''})`
            );
        }

        initCriticalBatch();
        scheduleDebugAudits();
    }

    // ── Debug-build audits (CONFIG.enableLogging only) ─────────────────────
    // Two silent-failure classes nothing else reports: an unregistered inline
    // icon paints a solid box (no CSS rule → computed mask-image 'none'), and
    // a promise-grammar container no component claimed stays skeleton-held
    // forever. Console-only; production builds never schedule this.
    // Runs 3s after the deferred icons CSS lands so injected bundles have
    // initialized and mask rules are computable.
    function runDebugAudits() {
        document.querySelectorAll('[data-filter-items]:not([data-nds-filter-initialized])').forEach(el => {
            if (el.closest('code, .code-example')) return;
            console.warn('[NDS] audit: data-filter-items container never claimed by a filter — it stays skeleton-held. Remove the attribute or add the filter UI.', el);
        });
        document.querySelectorAll('.nds-paged-content:not([data-paged-initialized])').forEach(el => {
            if (el.closest('code, .code-example')) return;
            console.warn('[NDS] audit: .nds-paged-content has no pagination nav — it stays skeleton-held and its data-paged-* slots never stamp. Unpaged lists use a plain container + data-filter-count.', el);
        });
        document.querySelectorAll('.nds-icon[class*="nds-hgi-"]').forEach(el => {
            if (el.closest('code, .code-example')) return;
            // The glyph paints on ::before (mask: var(--nds-icon) …), so read the
            // pseudo — the element itself never carries a mask.
            const cs = getComputedStyle(el, '::before');
            const masked = (cs.maskImage && cs.maskImage !== 'none')
                || (cs.webkitMaskImage && cs.webkitMaskImage !== 'none');
            if (!masked) {
                const cls = [...el.classList].find(c => c.startsWith('nds-hgi-'));
                console.warn(`[NDS] audit: inline icon "${cls}" is not in the registered set and paints as a solid box. Use the HGI font class: <i class="hgi hgi-stroke ${cls.replace('nds-', '')}">`, el);
            }
        });
    }

    function scheduleDebugAudits() {
        if (!CONFIG.enableLogging) return;
        // Icons CSS is loader-deferred; poll for its stamp (capped) rather than
        // holding an observer open. Debug builds only, so the poll is free.
        let tries = 0;
        const timer = setInterval(() => {
            const iconsReady = document.documentElement.hasAttribute('data-nds-icons-loaded');
            if (iconsReady || ++tries > 20) {
                clearInterval(timer);
                setTimeout(runDebugAudits, 3000);
            }
        }, 500);
    }

    // Configuration options
    // Merge defaults with optional global/window overrides and HTML data-attributes
    // To enable performance monitoring, set window.NDSInitConfig = { enableTiming: true, enableLogging: true }
    // Note: NDSInitConfig uses window.* because it's set BEFORE the bundle loads (NDS namespace doesn't exist yet)
    const rootEl = document.documentElement;
    const attrAutoInit = rootEl?.getAttribute('data-nds-auto-init');
    const attrDisableAll = rootEl?.getAttribute('data-nds-disable-all');
    const GLOBAL = window.NDSInitConfig || {};

    const CONFIG = {
        // Per-batch budget: critical components init in a tight loop until this
        // many ms elapse, then yield. Keep below ~40 to stay clear of TBT's
        // 50ms long-task threshold even on throttled CPUs.
        initBudgetMs: GLOBAL.initBudgetMs ?? 5,
        enableLogging: GLOBAL.enableLogging ?? false,
        enableTiming: GLOBAL.enableTiming ?? false,
        // When false, prevents automatic initialization on DOM ready
        autoInitialize: GLOBAL.autoInitialize ?? (attrAutoInit != null ? attrAutoInit !== 'false' : true),
        // When true, disables initializing any component (manual calls still respected if caller overrides)
        disableAll: GLOBAL.disableAll ?? (attrDisableAll != null ? attrDisableAll === 'true' : false),
    };

    // On-demand bundle loader for content injected after page load:
    //   await NDS.loadBundle('extras'); NDS.Chart.init();
    // Cheaper than re-running NDS.Init.initialize() (no full re-sweep / re-tag).
    NDS.loadBundle = loadBundle;
    // Back-compat shim for consumers of the built bundle still calling the old
    // extras-specific API.
    NDS.loadExtras = () => loadBundle('extras');

    // Expose global API immediately
    NDS.Init = {
        initialize: initializeNDS,
        components: COMPONENTS,
        config: CONFIG,
        // On-demand run of the debug audits (unregistered inline icons,
        // unclaimed filter/paged containers) — callable from any console or
        // test harness regardless of the enableLogging flag, which only
        // controls the automatic post-init sweep.
        audit: runDebugAudits,
    };

    // Initialize when ready (if enabled). main runs as a defer script, so when
    // this executes the DOM is already fully parsed (readyState 'interactive') —
    // we do NOT wait for DOMContentLoaded, because DCL also waits for every OTHER
    // defer script (showcase, accessibility, page custom_js) to download + execute,
    // which would let them gate the reveal. Kicking off via a macrotask starts the
    // reveal off main alone, off main's eval task. Only the rare sync-in-<head>
    // case (readyState 'loading', DOM not yet parsed) waits for DCL.
    if (CONFIG.autoInitialize) {
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', initializeNDS);
        } else {
            setTimeout(initializeNDS, 0);
        }
    }
})();
